### ISSUE TITLE
form表单中input输入时报错Cannot read property 'selectComponent' of undefined

### ISSUE THREAD

**Issue by winter-ice** [TaleLin/lin-ui#1050]
**LinUI版本（必填）：0.8.8

**设备（必填）：开发者工具

**基础库版本（必填）：2.12.1

**UI问题，请附上截图**

**重现步骤，必要时请提供代码片段链接**
```
    <l-form >
        <l-form-item label="产品名" name="name">
            <l-input id="name" value="{{name}}" hide-label/>
        </l-form-item>
    </l-form>
```
```
MiniProgramError
Cannot read property 'selectComponent' of undefined
TypeError: Cannot read property 'selectComponent' of undefined
    at http://127.0.0.1:15142/appservice/miniprogram_npm/lin-ui/form/index.js:104:19
    at http://127.0.0.1:15142/appservice/miniprogram_npm/lin-ui/form/index.js:83:9
    at Array.forEach (<anonymous>)
    at Xe._forEachNodes (http://127.0.0.1:15142/appservice/miniprogram_npm/lin-ui/form/index.js:82:27)
    at Xe._getValues (http://127.0.0.1:15142/appservice/miniprogram_npm/lin-ui/form/index.js:102:19)
    at Xe._validateItem (http://127.0.0.1:15142/appservice/miniprogram_npm/lin-ui/form/index.js:72:20)
    at Function.<anonymous> (http://127.0.0.1:15142/appservice/miniprogram_npm/lin-ui/form/index.js:65:17)
    at <setTimeout callback function>
    at http://127.0.0.1:15142/appservice/__dev__/WAService.js:2:121816
    at http://127.0.0.1:15142/appservice/__dev__/WAService.js:2:113742
```

**Comment by winter-ice** [comment]
使用 form 组件时需要在 `onLoad` 中调用 `wx.lin.initValidateForm(this)` 进行初始化。
