### ISSUE TITLE
源码克隆，npm run build 异常

### ISSUE THREAD

**Issue by memoryoverflow** [TaleLin/lin-ui#1382]
**设备型号：Mac**

**LinUI 版本：0.9.4**

**微信小程序基础库版本：**

**问题描述及重现步骤：**
git clone

npm install

npm run build 

异常信息：

```
MacBook-Pro lin-ui $ npm run build

lin-ui@0.9.4 build /Users/yongjian/work/lin-ui
> gulp -f build/index.js build

internal/modules/cjs/loader.js:625
  throw e;
  ^

Error: No valid exports main found for '/Users/yongjian/work/lin-ui/node_modules/copy-props/node_modules/is-plain-object'
    at resolveExportsTarget (internal/modules/cjs/loader.js:622:9)
    at applyExports (internal/modules/cjs/loader.js:499:14)
    at resolveExports (internal/modules/cjs/loader.js:548:12)
    at Function.Module._findPath (internal/modules/cjs/loader.js:654:22)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:953:27)
    at Function.Module._load (internal/modules/cjs/loader.js:859:27)
    at Module.require (internal/modules/cjs/loader.js:1028:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/Users/yongjian/work/lin-ui/node_modules/copy-props/index.js:4:21)
    at Module._compile (internal/modules/cjs/loader.js:1139:30) {
  code: 'MODULE_NOT_FOUND'
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! lin-ui@0.9.4 build: `gulp -f build/index.js build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the lin-ui@0.9.4 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/yongjian/.npm/_logs/2021-04-30T09_14_03_453Z-debug.log

```

**相关截图**：

**Comment by jiangjiali** [comment]
一定是你的npm install 没有安装完整吧。我完全没有遇到这种情况。
