### ISSUE TITLE
安装后小程序构建npm后出现路径错误

### ISSUE THREAD

**Issue by s2265681** [TaleLin/lin-ui#315]
**重现步骤（可选）：**

**期望的结果是什么？**

**实际的结果是什么？**
VM679:5 Path must be a string. Received true
TypeError: Path must be a string. Received true

**Comment by 7insummer** [comment]
麻烦提供下更详细的说明，另外可再仔细参考下文档，文档在安装部分说的是非常清楚的了。包括，不要使用cnpm来安装等注意事项，小程序构建对cnpm是不太兼容的

**Comment by s2265681** [comment]
已经解决，安装构建完之后 ，我的需要把设置里面的npm模块关掉，否则会报下面的错 ， 使用没有问题
VM14363:5 Path must be a string. Received true
TypeError: Path must be a string. Received true
    at assertPath (path.js:28:11)
    at Object.join (path.js:1239:7)
    at b (/Applications/wechatwebdevtools.app/Contents/Resources/package.nw/js/fcadebce92dacc42ac4bba476b700dee.js:1:335)
    at Proxy.checkComponentPath (/Applications/wechatwebdevtools.app/Contents/Resources/package.nw/js/fcadebce92dacc42ac4bba476b700dee.js:1:984)
    at checkPageJSON (/Applications/wechatwebdevtools.app/Contents/Resources/package.nw/js/d260ebf687a29f24aed49f66b233ab7d.js:1:3515)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

**Comment by wsq815** [comment]
如果勾选“使用npm模块”，在构建的时候我遇到同样的问题（VM14363:5 Path must be a string. Received true
TypeError: Path must be a string. Received true
at assertPath (path.js:28:11)
at Object.join (path.js:1239:7)），当去掉勾选“使用npm模块的时候”会继续执行构建，报错就解决了。

**Comment by wsq815** [comment]
> 麻烦提供下更详细的说明，另外可再仔细参考下文档，文档在安装部分说的是非常清楚的了。包括，不要使用cnpm来安装等注意事项，小程序构建对cnpm是不太兼容的

我这边不是用cnpm安装的，用的是npm

**Comment by YpchenLove** [comment]
对这个问题，再做一个补充，还有一种情况下，需要删除构建后的miniprogram_npm，重启编辑器，勾选最新版本库，再次构建。
