### ISSUE TITLE
官方版本示例表单组件 Form 中的校验有bug

### ISSUE THREAD

**Issue by 270686992** [TaleLin/lin-ui#919]
**LinUI版本（必填）：0.8.3**

**设备（必填）：mac**

**基础库版本（必填）：2.11.0**

**UI问题，请附上截图**

**重现步骤，必要时请提供代码片段链接**
当第一次进入表单组件中的 Form 时去进行联合校验的时候是没有问题的,不会报错,如下图:
![在这里插入图片描述](https://img-blog.csdnimg.cn/20200620162751583.png)

然而,当点击左上角返回按钮再次重新进入表单组件中的 Form 时去进行联合校验的时候,报了这个错误,联合校验也失效了.
报错信息:
```
MiniProgramError
Cannot read property 'validatorData' of undefined
TypeError: Cannot read property 'validatorData' of undefined
    at Ge._validateItem (http://127.0.0.1:45483/appservice/dist/form/index.js:110:23)
    at Object.v (http://127.0.0.1:45483/appservice/dist/form/index.js:76:16)
    at EventBus.emit (http://127.0.0.1:45483/appservice/dist/core/utils/event-bus.js:53:22)
    at Ge.handleInputBlur (http://127.0.0.1:45483/appservice/dist/input/index.js:116:25)
    at Object.r.safeCallback (http://127.0.0.1:45483/appservice/__dev__/WAService.js:2:1755112)
    at http://127.0.0.1:45483/appservice/__dev__/WAService.js:2:1891345
    at r (http://127.0.0.1:45483/appservice/__dev__/WAService.js:2:1832361)
    at http://127.0.0.1:45483/appservice/__dev__/WAService.js:2:1832483
    at http://127.0.0.1:45483/appservice/__dev__/WAService.js:2:904608
    at n (http://127.0.0.1:45483/appservice/__dev__/asdebug.js:1:27036)
```
报错的截图:
![在这里插入图片描述](https://img-blog.csdnimg.cn/20200620163048498.png)

**Comment by juzi214032** [comment]
感谢反馈，下个版本将会修复
